
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxdesajqgvecedenenxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZGVzYWpxZ3ZlY2VkZW5lbnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTgxOTgsImV4cCI6MjA2NTU3NDE5OH0.Abg6U_CJO0I-NF82VkInT8o3m4POViehHSTeaJXHLa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
